pcodec/pcodec

- example/generate_randoms.py
Currently running `python generate_randoms.py` following the example instructions can result in this `FileNotFoundError` error:
```
FileNotFoundError: [Errno 2] Failed to open local file 'data/snappy_parquet/i64_normal1.snappy.parquet'. Detail: [errno 2] No such file or directory
```
This seems to be because the `data/snappy_parquet` directory is never created in the script. This has been fixed in this PR. The script runs as expected when the data folder is empty (or non-existent) after this change.
> Add snappy_parquet directory to example data script

- .gitignore
- example/generate_randoms.py
- example/src/main.rs
- src/bits.rs
- src/lib.rs
- src/types/boolean.rs
- src/types/boolean8.rs
- src/types/mod.rs
Support for 8-bit (1 byte) booleans via a new `q_compress::types::boolean8::B8DataType` type
Some references:
- https://users.rust-lang.org/t/solved-what-is-byte-value-for-boolean/47347
- https://doc.rust-lang.org/std/primitive.bool.html
> Add boolean support

- examples/fast_seeking.rs
- examples/primary.rs
- src/bit_reader.rs
- src/decompressor.rs
- src/tests/backward_compatibility.rs
- src/tests/recovery.rs
- src/tests/stability.rs
Currently BitReader requires callers to give ownership of the data. Since it
actually never needs to have ownership, rework this so that BitReader instead
stores a reference to a byte slice. This allows callers not having to do unnecessary
copies of the raw data.
Note that this changes the public API (I haven't updated the changelog accordingly).
> Rework BitReader to use byte slices

- Cargo.lock
- Cargo.toml
- README.md
- q_compress/Cargo.toml
- q_compress/src/data_types/mod.rs
- q_compress/src/data_types/signeds.rs
- q_compress/src/data_types/unsigneds.rs
This adds the remaining standard integer types as `NumberLike`. Closes #31.
> added 16-bit and i128 support

- Cargo.lock
- benchmarks.md
- q_compress/Cargo.toml
- q_compress/changelog.md
- q_compress/examples/fast_seeking.rs
- q_compress/src/bit_reader.rs
- q_compress/src/bit_words.rs
- q_compress/src/bit_writer.rs
- q_compress/src/bits.rs
- q_compress/src/constants.rs
- q_compress/src/data_types/mod.rs
- q_compress/src/data_types/unsigneds.rs
- q_compress/src/decompressor.rs
- q_compress/src/delta_encoding.rs
- q_compress/src/errors.rs
- q_compress/src/huffman_decoding.rs
- q_compress/src/lib.rs
- q_compress/src/prefix.rs
- q_compress/src/tests/low_level.rs
- q_compress/src/tests/stability.rs
- q_compress_cli/src/inspect_handler.rs
* Using BitReader operating on `usize` instead of `u8`
* Allowing variable-sized Huffman decompression tables
> Decompression performance boost

- q_compress/examples/generate_randoms.py
- q_compress/src/bits.rs
- q_compress/src/compressor.rs
- q_compress/src/constants.rs
- q_compress/src/prefix_optimization.rs
* Reduced number of prefixes used for small data. Default compression ratio should balance compression time vs compressed size for all n (defaulting to 256 was especially slow in the 100 < n < 16k range). E.g. in the 2^10 <= n < 2^12 range this uses up to 64 prefixes by default.
* Improved prefix optimization speed by about 30%.
* Added a new dataset of decimal-valued floats
> Small data compression performance

- q_compress/src/base_compressor.rs
- q_compress/src/huffman_encoding.rs
- q_compress/src/num_decompressor.rs
- q_compress/src/prefix.rs
- q_compress/src/prefix_optimization.rs
- q_compress/src/run_len_utils.rs
- q_compress/src/tests/recovery.rs
- rustfmt.toml
Improved compression in some important cases; some performance loss at very high compression levels.
I am baffled that I was able to do this (something I had initially thought difficult) while decreasing source code size.
> Run Length for nontrivial prefixes

- q_compress/changelog.md
- q_compress/src/gcd_utils.rs
often saves a few hundred bytes
> Actually use common gcd

- durendal/src/data_types/floats.rs
- durendal/src/data_types/unsigneds.rs
- durendal/src/tests/recovery.rs
I had a bug when there were also numbers above 2^bits in magnitude. This may also improve compression ratio for floats between 2^mantissa and 2^bits.
> Float mult fix

- README.md
- bench/src/codecs/pco.rs
- pco/src/ans/decoding.rs
- pco/src/auto.rs
- pco/src/base_compressor.rs
- pco/src/base_decompressor.rs
- pco/src/bin.rs
- pco/src/body_decompressor.rs
- pco/src/chunk_metadata.rs
- pco/src/flags.rs
- pco/src/lib.rs
- pco/src/modes/mode.rs
- pco/src/num_decompressor.rs
- pco/src/standalone/compressor.rs
- pco/src/standalone/simple.rs
- pco/src/tests/atomicity.rs
- pco/src/tests/low_level.rs
- pco/src/tests/recovery.rs
- pco/src/tests/stability.rs
- pco/src/tests/utils.rs
- pco/src/tests/wrapped.rs
- pco/src/unsigned_src_dst.rs
- pco/src/wrapped/compressor.rs
- pco_cli/src/compress_handler.rs
- pco_cli/src/inspect_handler.rs
Use faster loops for more trivial cases. This also paves the way to enabling optional lossy float mult compression and decompression
> Better loop choice

- pco_cli/generate_randoms.py
- Allow user to specify which datasets to generate
- Allow user to specify where to write the output data
- Change global variables to local where possible
Smoke-tested at the command line:
- Ran with no arguments, produced same behavior as before the change
- Specified a subset of the datasets, only those were created
- Specified a different output dir, it was used
> Minor improvements to `generate_randoms.py`

- pco_python/src/lib.rs
- pco_python/src/standalone.rs
- pco_python/src/wrapped/compressor.rs
- pco_python/src/wrapped/decompressor.rs
- pco_python/test/test_standalone.py
- pco_python/test/test_wrapped.py
The notorious CPython GIL prevents threaded true parallelism in Python code. External code may choose to release the GIL to allow threaded parallelism for specific sections of the code. This can provide huge performance benefits in cases where most of the work can safely be done outside of Python. A common example is a Python web server, where threads are often used for async operations, but will also benefit performance when work can be performed outside the GIL.
``` python
iterations = 10
dur = 0
for i in range(iterations):
com_f16_frames = []
start = time()
com_f16_frames = [standalone.simple_compress(f, config) for f in in_f16]
dur += (time() - start) / iterations
print(f"{len(com_f16_frames) / dur:.0f} FPS")
print(f"{in_f16.nbytes / dur / 1000**2:.0f} MB/s")
dur = 0
with …
```
> Release CPython GIL using `allow_threads`

- pco_cli/generate_randoms.py
- pco_cli/src/bench/mod.rs
- pco_cli/src/input/audio.rs
* added f16_normal to generate_randoms.py
* interpreted most wav data as 16-bit instead of 32-bit now
* fixed issue where `bench` printed out the fully qualified type name for f16 (half): `│ half::binary16::f16_normal │ pco   │   19.8805ms │    1.790916ms │         1691993 │`
> f16 dataset, 16-bit wavs, fixed f16 naming in bench subcommand

- pco_python/src/lib.rs
- pco_python/test/test_standalone.py
- pco_python/test/test_wrapped.py
This PR adds missing options to the `PyChunkConfig` and aligns it with `ChunkConfig`. This is done by adding three new wrapper classes. 
`PyFloatMultSpec` and `PyFloatQuantSpec` are used for the `int_mult_spec` and `float_mult_spec` properties instead of `String`. This allows `base` values to passed in using the `provided` function. `Enabled` and `Disabled` are now set using the `enabled` and `disabled` functions, rather than passing in strings.
The `float_quant_spec` property of type `PyFloatQuantSpec` has been added to `PyChunkConfig`. This works similar to the other two wrappers.
This fixes #202.
> Added missing options to `PyChunkConfig`, fixes #202

- .github/workflows/python.yml
- pco_cli/generate_randoms.py
- pco_python/test/test_standalone.py
- pco_python/test/test_wrapped.py
Default Ruff settings used. Command:
``` bash
ruff check --select I --fix .
ruff format .
```
> Formatted Python files with ruff 0.4.9, fixes #205

- pco/Cargo.toml
- pco_c/Cargo.toml
- pco_cli/Cargo.toml
- pco_python/Cargo.toml
The `half` minimum version is relaxed from 2.4.1 to 2.0.0 for most of the `pco` crates.
For `pco_cli`, `half` is relaxed to 2.1.0 and `bytes` increased from 1.1.0 to 1.4.0.
These minimum versions are set by the `arrow` related deps.
> Revise minimum versions of `half` and `bytes`

- pco/src/bin_optimization.rs
This PR replaces `log2()` with `log(2.0)` on Windows. The motivation is that `log2()` is *very* slow on Windows making `log(2.0)` about 10x faster.
See #223 for more details.
> Replaced `log2()` with `log(2.0)` on Windows, fixes #223

- pco/src/histograms.rs
The current `slice_min` and `slice_max` functions are not very clean, [nor do they seem to vectorize](https://rust.godbolt.org/z/537xGvj8r).
I've replaced the for-loops with `latents.iter().fold()`, which appears to be vectorized by the compiler.
I've added a new `slice_min_max` function that gets both values in one iteration. To use this effectively I've had to make a change to `apply_incomplete`, which I admit is not the cleanest. Suggestions are welcome!
~~Honestly, I'm not able to see any repeatable change in performance when running the benchmarks. I've done some digging and it appears the time spent in the min-max functions is so little that I cannot properly benchmark it.~~
~~@mwlon, do you know any scenarios which will cause more time to be spent in these functions that we could …
> Simpler min-max functions that vectorize

- pco_cli/generate_randoms.py
The function
``` python
@datagen("i64")
def uniform():
return np.random.randint(-(2**63), 2**63, size=max_n)[:n]
```
raises an error on Windows due to using `i32` type.
```
Traceback (most recent call last):
File "...\generate_randoms.py", line 352, in <module>
data = f()
File "...\generate_randoms.py", line 129, in uniform
return np.random.randint(-(2**63), 2**63, size=max_n)[:n]
File "numpy\\random\\mtrand.pyx", line 780, in numpy.random.mtrand.RandomState.randint
File "numpy\\random\\_bounded_integers.pyx", line 2877, in numpy.random._bounded_integers._rand_int32
ValueError: low is out of bounds for int32
```
Specifying `dtype=np.int64` fixes this.
> Fixed out-of-bounds when generating random on Windows

- pco_cli/src/input/audio.rs
Check WAV header audio format and bit per sample to select proper data type for WAV samples. Fixes issues with multichannel WAV files #230.
> Better WAV-file support, fixes #230

- pco/src/delta.rs
- pco_cli/src/dtypes.rs
Simplifies code and benchmarks indicate this change will improve performance.
```
cargo run --release -- bench -i data/binary/ --input-format binary -d interl --iters 100
Laptop (Intel® Core™ i7-1370P Processor):
main:
╭─────────────────────┬───────┬─────────────┬───────────────┬─────────────────╮      
│ dataset             │ codec │ compress_dt │ decompress_dt │ compressed_size │      
├─────────────────────┼───────┼─────────────┼───────────────┼─────────────────┤      
│ i32_interl0         │ pco   │  58.78775ms │     4.01065ms │          890794 │      
│ i64_interl0         │ pco   │  62.42405ms │      4.7225ms │          891168 │      
│ i32_interl1         │ pco   │   59.0238ms │      3.9483ms │          541198 │      
│ i64_interl1         │ pco   │  64.43565ms │     4.83275ms │ …
```
> Removed `lookback_goodness_argmax`

- Cargo.lock
- pco_cli/Cargo.toml
- pco_cli/src/bench/codecs/vortex.rs
Firstly, thank you for taking the time to benchmark Vortex!
I've removed the explicit compression as the writer will do that on its own, and slimmed the dependency by a bit. 
We're also planning on improving on some of the pain points here (Sync read/write, less copies when working with `&[u8]`).
Running `pcodec bench -c pco,vortex` on my macbook now shows:
```
╭──────────────────────┬────────┬──────────────┬───────────────┬─────────────────╮
│ dataset              │ codec  │  compress_dt │ decompress_dt │ compressed_size │
├──────────────────────┼────────┼──────────────┼───────────────┼─────────────────┤
│ i64_cents            │ pco    │  11.239875ms │    2.053458ms │          443472 │
│ i64_cents            │ vortex │   9.359812ms │    1.228125ms │          879908 │
│ i64_constant …
```
> Vortex benchmark touchups

- pco/src/metadata/page.rs
- pco/src/metadata/per_latent_var.rs
Builder is more verbose than .map, and might copy the data in some cases.
> use less PerLatentVarBuilder

- pco/Cargo.toml
- pco/build.rs
I kept thinking about how to ensure good performance, since these instruction sets aren't enabled by default (at least on an old machine of mine that DOES support them). I considered forcing them to be on, without input from the user, but ultimately decided that would be confusing behavior and could cause problems if the user really doesn't have them. Instead I think this warning is the right middle ground, but open to input if there are other conventions out there.
I tried it out and got the warning as expected, and didn't get it when using the instruction sets.
> Warn if compiled on x64 in release without avx, bmi

- pco/src/latent_page_decompressor.rs
- pco/src/tests/stack_sizes.rs
- pco/src/wrapped/page_decompressor.rs
With `pco bench --limit 100 --iters 10000` I now get 41us instead of 127us on my machine. Without the limit, performance is unaffected within measurement error.
#259
> heap allocate LatentPageDecompressors

- .cargo/config_for_publishing.toml
- .github/workflows/java_publish.yml
- .github/workflows/python_publish.yml
- pco_java/pom.xml
* specify rust toolchain for python
* specify project name for java
* use a cargo config instead of both cargo config and rustflags (which might not work?)
> FFI publishing fix

- docs/CONTRIBUTING.md
As written, I think the shell will attempt to expand the glob pattern and so `pytest` won't see the glob pattern, which is not what we want.
> I think this shell command needs quotes?

- pco/src/standalone/decompressor.rs
- pco/src/standalone/simple.rs
- pco_java/src/main/rust/src/lib.rs
- pco_python/src/lib.rs
- pco_python/src/standalone.rs
- pco_python/test/test_standalone.py
Shared decompression logic with the main crate so that it's harder to mess up.
This bug would only appear in standalone and when running on ancient data or data written by the low-level APIs without an n_hint.
The problem was that we only set the dst vector's capacity according to `n_hint`, which is only a hint and not always present, but kept increasing its length and writing to the end, which could cause a segfault:
```rust
let mut res: Vec<T> = Vec::with_capacity(n_hint);  // reasonable start
while let MaybeChunkDecompressor::Some(mut chunk_decompressor) = ... {
let initial_len = res.len();
let remaining = chunk_decompressor.n();
unsafe {
res.set_len(initial_len + remaining); // DANGER
}
let progress = chunk_decompressor.decompress(&mut res[initial_len..])?;  // DANGER
```
> Fix standalone decompression bug in FFI libs when no n_hint is present

- .cargo/config.toml
Hi, there is an error when I try to build on MacOS with M1 chip.
error: linking with `cc` failed: exit status: 1
According to the documentation of PYO3, I fix the problem successfully.
https://pyo3.rs/v0.20.2/building_and_distribution#macos
> fix cargo build on macos;

- pco_cli/src/bench/codecs/blosc.rs
- pco_cli/src/bench/mod.rs
- pco_cli/src/input/mod.rs
* For binary input format, support dtype at end of filename instead of start
* Wrap Blosc to support byte size > 2^31
* Fixed a lint
> FCBench CLI tweaks

- pco/src/compression_table.rs
- pco/src/latent_batch_dissector.rs
On my machine at level 0 this was about a 50-60% speedup on the lomax05 dataset. 2/3 of these shortcuts only really apply to level 0, but the 3rd one is still a slight speedup at other low compression levels, e.g. ~4% at level 2.
> Faster low compression levels

- pco/src/chunk_config.rs
- pco/src/wrapped/page_decompressor.rs
- pco_cli/src/bench/codecs/mod.rs
- pco_cli/src/bench/codecs/pcopage.rs
- pco_cli/src/chunk_config_opt.rs
This also exposes the n_per_page function from `PagingSpec`, which seems useful and pretty stable.
Results on the synthetic benchmarks:
```
╭──────────────────────┬──────────────────────┬──────────────┬───────────────┬─────────────────╮
│ dataset              │ codec                │  compress_dt │ decompress_dt │ compressed_size │
├──────────────────────┼──────────────────────┼──────────────┼───────────────┼─────────────────┤
│ <sum>                │ pco                  │ 775.966545ms │  107.237332ms │        65130478 │
│ <sum>                │ pcopage              │ 779.716631ms │   105.45725ms │        65131097 │
│ <sum>                │ pcopage:page-n=10000 │ 791.262913ms │  118.611795ms │        65271329 │
│ <sum>                │ pcopage:page-n=1000  │ 844.302709ms │  227.338416ms …
```
> Added paginated pco format to benchmarks
